# docker-compose.yml
version: '3'
services:
  flask:
    image: dnp-flask
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - "./:/app"
    ports:
      - 5000:5000
    working_dir: /app/server
    command: python aqiserver.py 
    
    